### ISSUE TITLE
Could you add Powerbeats Pro support

### ISSUE THREAD

**Issue by Denis4yk** [Acidham/alfred-airpod-connector#1]
Fortunately, not only AirPods use the H1 chip. Could you add Powerbeats Pro too?

This is the link to those. I have no idea about their product code, to be honest :D 
https://www.bestbuy.com/site/beats-by-dr-dre-powerbeats-pro-totally-wireless-earphones-black/6341988.p?skuId=6341988&intl=nosplash

**Comment by Acidham** [comment]
I can try...I assume you own such devices and paired to your mac? In this case I need VendorID and ProductID under DeviceCache in /Library/Preferences/com.apple.Bluetooth.plist

To open the file you need a plist editor or you send the file to me and I will have look at it.

**Comment by Denis4yk** [comment]
```xml
		<dict>
			<key>AccessoryFWVersion</key>
			<string>2C48</string>
			<key>BatteryPercentCase</key>
			<integer>43</integer>
			<key>BatteryPercentLeft</key>
			<integer>98</integer>
			<key>BatteryPercentRight</key>
			<integer>98</integer>
			<key>ClassOfDevice</key>
			<integer>2360344</integer>
			<key>ClockOffset</key>
			<integer>0</integer>
			<key>EncryptionKeySize</key>
			<integer>16</integer>
			<key>ExtendedFeaturesPage1</key>
			<data>
			AAAAAAAAAAc=
			</data>
			<key>FirstPairing</key>
			<true/>
			<key>HeySiriEnabled</key>
			<integer>1</integer>
			<key>InEar</key>
			<false/>
			<key>LMPSubversion</key>
			<integer>32049</integer>
			<key>LMPVersion</key>
			<integer>9</integer>
			<key>LastInquiryUpdate</key>
			<date>2020-07-10T14:45:09Z</date>
			<key>LastServicesUpdate</key>
			<date>2020-07-10T14:45:10Z</date>
			<key>LeftDoubleTap</key>
			<integer>3</integer>
			<key>Manufacturer</key>
			<integer>76</integer>
			<key>Name</key>
			<string>Денис’s Powerbeats Pro</string>
			<key>PageScanMode</key>
			<integer>0</integer>
			<key>PageScanPeriod</key>
			<integer>0</integer>
			<key>PageScanRepetitionMode</key>
			<integer>1</integer>
			<key>PrimaryBud</key>
			<integer>2</integer>
			<key>PrimaryInEar</key>
			<integer>2</integer>
			<key>ProductID</key>
			<integer>8203</integer>
			<key>RightDoubleTap</key>
			<integer>3</integer>
			<key>SecondaryInEar</key>
			<integer>2</integer>
			<key>ServiceMask</key>
			<integer>1581081</integer>
			<key>Services</key>
			<data>
			long-ass code...
			</data>
			<key>SupportedFeatures</key>
			<data>
			h3v/2/4v/r8=
			</data>
			<key>VendorID</key>
			<integer>76</integer>
			<key>displayName</key>
			<string>Денис’s Powerbeats Pro</string>
		</dict>
```

**Comment by Denis4yk** [comment]
This stuff is made by apple, so pairing should be similar to AirPods.

**Comment by Denis4yk** [comment]
BTW, if I've copied smth wrong, let me know :)

**Comment by Acidham** [comment]
Please test...

**Comment by Denis4yk** [comment]
Bingo! Works like a charm :D 

Thanks) 

The only question is the color. I have white ones...but who really cares, to be honest :D 


<img width="582" alt="Screenshot 2020-07-13 at 15 30 46" src="https://user-images.githubusercontent.com/15350325/87304701-e2eb0d00-c51d-11ea-9899-f16b4dc07787.png">

**Comment by Denis4yk** [comment]
Thanks, man! I'm using it from now as a default one :)

**Comment by Acidham** [comment]
I was not able to find white ones, and I was too lazy to change to white. If you want you can do that for case and for the headset and I will change ;)

**Comment by Acidham** [comment]
I did just an color invert for powerbeats. Please download v1.2.1 and try if this works
