### ISSUE TITLE
debug console shows /bin/sh: blueutil: command not found

### ISSUE THREAD

**Issue by rick-yao** [Acidham/alfred-airpod-connector#12]
I have installed blueutil
❯ blueutil
Power: 1
Discoverable: 0

and my default shell is zsh. 
But seems the workflow cannot detect blueutil
debug console output :
[16:57:29.023] AirPods Connector[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8E5968B1-B63E-43E2-9E62-1BE7A5E80ACE%3E2378081C-843E-45C6-B549-1B0FFD46EF7C)] Queuing argument '(null)'
[16:57:29.159] AirPods Connector[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8E5968B1-B63E-43E2-9E62-1BE7A5E80ACE%3E2378081C-843E-45C6-B549-1B0FFD46EF7C)] Script with argv '(null)' finished
[16:57:29.163] STDERR: AirPods Connector[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8E5968B1-B63E-43E2-9E62-1BE7A5E80ACE%3E2378081C-843E-45C6-B549-1B0FFD46EF7C)] /bin/sh: blueutil: command not found
[16:57:29.163] AirPods Connector[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8E5968B1-B63E-43E2-9E62-1BE7A5E80ACE%3E2378081C-843E-45C6-B549-1B0FFD46EF7C)] {

**Comment by Acidham** [comment]
Seems `blueutil` is not in path. Can you please open the workflow > /bin/zsh step and add the following line at the beginning:

```
source ~/.zshrc
```

the script should then look like:

```
source ~/.zshrc
./py3.sh con_manager.py "$1"
```

**Comment by rick-yao** [comment]
thanks for your quick reply but the solution you provided did not work.
I also tried 'zsh ./py3.sh con_manager.py "$1"'   but still didn't work.
I installed blueutil via brew , is it somehow relevant to this ?

**Comment by Acidham** [comment]
The issue is that the shell is not loaded, and it seems the path to `blueutil` is not loaded. Can you exec `where blueutil` on terminal?

**Comment by rick-yao** [comment]
Yes , please check below output.
~
❯ where blueutil
/opt/homebrew/bin/blueutil
/opt/homebrew/bin/blueutil

~
❯ which blueutil
/opt/homebrew/bin/blueutil

~
❯

**Comment by Acidham** [comment]
ok can you please download update WF: https://github.com/Acidham/alfred-airpod-connector/blob/master/AirPods%20Connector.alfredworkflow

please tell me if it now works

**Comment by rick-yao** [comment]
I tried the updated version. It still didn't work. But there is one difference. please check the img below.
<img width="841" alt="image" src="https://user-images.githubusercontent.com/59443488/208242551-997102f7-ee24-46d8-9f5c-3d886017790d.png">

**Comment by Acidham** [comment]
can you please try to re-install blueutil

**Comment by rick-yao** [comment]
yes , I uninstalled and re-installed it just now but didn't resolve the issue.
I checked that bash can also detects blueutil.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/59443488/208243635-a294978a-40a1-41e6-8fcb-bebe91a03617.png">

**Comment by rick-yao** [comment]
My python3 version 
❯ python3 --version
Python 3.10.9

not sure if this affects

**Comment by Acidham** [comment]
as mentioned before the path cannot be found.

what macOS are you using ?

normally should be on zsh not bash

**Comment by Acidham** [comment]
you can add into last WF step the following 

`PATH=/opt/homebrew/bin`

then it works

**Comment by rick-yao** [comment]
I am using zsh , I just tried bash.
Did you mean to add Path like the following ?
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/59443488/208245230-1479ce3f-222b-4e9f-a58d-be111f119567.png">

**Comment by Acidham** [comment]
yes exactly but please use this line, forgot to add $PATH: `PATH=$PATH:/opt/homebrew/bin`

**Comment by Acidham** [comment]
Bu there is something wrong with your set up. Usually `/opt/homebrew/bin` is part of a standard shell. 

Can you please help to investigate? 

1. What is being returned when you exec `echo $SHELL`
2. What is being returned when you exec `cat ~/.zprofile`

**Comment by rick-yao** [comment]
ahhh...still don't work after adding Path line.
below is the output as per your request.
❯ echo $SHELL
/bin/zsh

~
❯ cat ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"


# Added by Toolbox App
export PATH="$PATH:/Users/rick/Library/Application Support/JetBrains/Toolbox/scripts"


~
❯

**Comment by Acidham** [comment]
Can you add export to the PATH in the workflow step as well, forgot to add it in my previous post:
`export PATH=$PATH:/opt/homebrew/bin`

**Comment by rick-yao** [comment]
Thanks , final solution should be 
"
export PATH=$PATH:/opt/homebrew/bin
./py3.sh con_manager.py "$1"
"
source command is not needed. 
Thanks for your patience !

**Comment by Acidham** [comment]
But anyhow, something is wrong with your setup because it should be loaded in shellenv properly.

I will leave the export and release it. Should not hurt others.
