### ISSUE TITLE
Not working for me 🤷‍♂️

### ISSUE THREAD

**Issue by erikdstock** [Acidham/alfred-airpod-connector#13]
I have `blueutil` installed and the menu item appears showing my airpods but connect/disconnect does nothing. Happy to give more logs if you tell me how. OS Ventura 13.1, M1 macbook pro.

**Comment by Acidham** [comment]
Are you seeing any error in Alfred debugger?

Open Alfred debugger, click the bug icon too left in Alfred Preferences.

**Comment by erikdstock** [comment]
Ah thanks for the tip - I realized i actually had installed the wrong bluetooth utility, debugger tipped me off. Closing and please do NOT tell anyone about this!
