### ISSUE TITLE
Not working? Do i need to instal python?

### ISSUE THREAD

**Issue by benkhademi** [Acidham/alfred-airpod-connector#14]
Hi,

I just downloaded the workflow and set it up vanilla. Is there anything else i need to do to get it to work?

When i try to connect to my airpods it never works. Thanks for help

**Comment by Acidham** [comment]
Did you install bluetutil? What is the Workflow debugger showing when executing the workflow?

**Comment by benkhademi** [comment]
Sorry, i just saw that we need to download bluetutil. It works great!
