### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by 3raxton** [Acidham/alfred-airpod-connector#2]
Thanks so much for taking the time to make this as it has greatly enhanced the experience on my Mac. What theme are you using for Alfred? I love how fresh it looks.

**Comment by Acidham** [comment]
Great to hear that the WF is valuable for you!

I am using the Frosty Dark theme by LiSongcheng with some minor adjustments: https://db.tt/5o0usLEo7l

**Comment by 3raxton** [comment]
Thanks for sharing that with me! Glad you built this, it helps me immensely
