### ISSUE TITLE
AirPods 3rd gen not working?

### ISSUE THREAD

**Issue by minor-coder** [Acidham/alfred-airpod-connector#9]
Not all Alfred workflows, including this one, will work :(

**Comment by Acidham** [comment]
Yes because I am not owning AirPods 3rd generation. If you can provide me with the info requested here and will add it: https://github.com/Acidham/alfred-airpod-connector/issues/1#issuecomment-657230457

**Comment by tiems90** [comment]
I just had a look myself and it looks like for the AirPods 3rd gen and got the following info:

VendorID = 76
ProductID = 8211

**Comment by Acidham** [comment]
Thank you...added Airpod3 support. Please download from repo and try

**Comment by tiems90** [comment]
It works! Amazing! Thanks so much 😊

**Comment by Acidham** [comment]
i will release it then
